### ISSUE TITLE
Planning Doc

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/charts#5]

**Comment by joshblack** [comment]
## Roadmap to v1.0.0

We should have the following charts implemented and usable:

- [ ] Bar chart
- [ ] Line chart
- [ ] Stacked bar chart
- [ ] Piechart
- [ ] Treemap
- [ ] Map
- [ ] Scatterplot
- [ ] Network (good WebGL candidate)
- [ ] Bubble chart
- [ ] Flows
- [ ] Heatmap
- [ ] Radar

And have the following languages/libraries/frameworks supported:

- [ ] Vanilla JS
- [x] React.js (Josh Black)
- [ ] Angular.js
- [ ] Ember.js
- [ ] Others?

If possible, find shepherds for each framework/library as necessary.

## Non-functional Requirements

Each language should have:

- [ ] Documentation
  - [ ] Usage
  - [ ] Examples
  - [ ] Contributing
- [ ] Tests
  - Coverage > 80%
- [ ] Research
  - Investigate Developer Experience
  - Understand needs of BUs and if we're helping service them
  - Review existing technologies, why do we need to build this?

## Project Organization

Should we leverage a mono-repo design?

**Comment by seejamescode** [comment]
My only concern with mono-repo is discoverability. If that is not a concern to @matthewgallo, @mhsenkow, and @tw15egan, then I have no objections.

Let's start with the React 1.0.0 version because I believe the Accurat examples are not in a library form. Then we can go back and extract from the React version the vanilla library.

Does that sound good?

**Comment by joshblack** [comment]
What do you mean by it impacting discoverability? And definitely, didn't realize the scope of the work didn't include it.

**Comment by seejamescode** [comment]
I just actually looked into Lerna and disagree with myself 2 minutes ago. We just need clear documentation in the main readme directing a discovering user to which dependency they want.

Yeah, Accurat only scoped to make the examples. I think it will be easy though to make the libraries since the examples are our desired outputs.
